# Generated by Django 5.1.6 on 2025-02-09 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom du type de depense')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la dépense')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant de la dépense')),
                ('moyen_paiement', models.CharField(choices=[('OR', 'Orange Money'), ('WAV', 'Wave'), ('FM', 'Free Money'), ('CB', 'Carte Bancaire'), ('ESP', 'Espèces'), ('CHQ', 'Chèque'), ('VIR', 'Virement')], default='Wav', max_length=10, null=True, verbose_name='Moyen de paiement')),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='justificatifs/', verbose_name='Pièce justificative')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utlisateur')),
                ('type_depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typedepense', verbose_name='type de dépense')),
            ],
        ),
    ]
