# Generated by Django 5.1.6 on 2025-02-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_typedepense_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='moyen_paiement',
            field=models.CharField(choices=[('OR', 'Orange Money'), ('WAV', 'Wave'), ('FM', 'Free Money'), ('CB', 'Carte Bancaire'), ('ESP', 'Espèces'), ('CHQ', 'Chèque'), ('VIR', 'Virement')], max_length=10, null=True, verbose_name='Moyen de paiement'),
        ),
    ]
