# Generated by Django 5.1.6 on 2025-02-13 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_is_admin_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='user',
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='depense',
            name='moyen_paiement',
            field=models.CharField(default='Cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='depense',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='depense',
            name='piece_justificative',
            field=models.FileField(blank=True, null=True, upload_to='depenses/'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='type_depense',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.typedepense'),
        ),
        migrations.AlterField(
            model_name='typedepense',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
