# Generated by Django 5.1.6 on 2025-02-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_depense_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='type_depense',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.typedepense'),
        ),
    ]
