# Generated by Django 5.1.6 on 2025-02-13 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_depense_type_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='type_depense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typedepense'),
        ),
    ]
